site_name: Note cr√©dit renouvelable
site_author: Quentin Godfroy
plugins: []
theme:
  name: readthedocs
  locale: fr
nav:
  - 0_resume_executif.md
  - 1_note_credit_revolving.md
  - 2_exemple.md
  - 3_exemple_d_offres.md
